config/routes.rb
Rails.application.routes.draw do
  root 'users#newhome'
  get 'signup', to: 'users#new'
  get 'home', to: 'users#home'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:alert] = "Logged in"
            redirect_to home_path
        else
            flash.now[:alert] = "Worng email and password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:alert] = "Logged out"
        redirect_to home_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:alert] = "user #{@user.name} updated"
      redirect_to home_path
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #direct login after signing process
      session[:user_id] = @user.id
      @user_name = cookies[:user_name]

      #alert for succesful user creation
      flash[:alert] = "User #{@user.name} signed up succesfully"
      redirect_to home_path 
    else
      render :new
    end
  end
  
  def show
  end

  def home
  end

  def newhome
  end

 private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end 

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="signup-form">
    <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.email_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update profile", class: "btn-primary") %>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
    <h1>Edit your profile</h1>
    <%= render partial: "form" %>
</div>

app/views/users/home.html.erb
<div class="container">
    <div class="flash-alert">
        <% if flash.any? %>
            <%= flash[:alert] %>
        <% end %>   
    </div>
    <h1>Welcome to the home page</h1>
    <% if logged_in? %>
        <%= link_to current_user.name, user_path(current_user) %>
        <%= link_to "Log Out", logout_path, method: :delete %> 
    <% else %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Sign Up", signup_path %>
    <% end %>
</div>    

app/views/users/new.html.erb
<div class="container">
    <h1>Sign Up</h1>
    <%= render partial: "form" %>
</div>

app/views/users/newhome.html.erb
<div class="container">
    <div class="flash-alert">
        <% if flash.any? %>
            <%= flash[:alert] %>
        <% end %>   
    </div>
    <h1>Welcome to the home page</h1>
    <% if logged_in? %>
        <%= link_to current_user.name, user_path(current_user) %>
        <%= link_to "Log Out", logout_path, method: :delete %> 
    <% else %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Sign Up", signup_path %>
    <% end %>
</div>  